#!/bin/sh      
 ssh -T root@52.21.166.231  <<EOF        
 cd /root/demoapp  
 git pull https://github.com/ranjith-urolime/demoapp.git      
 npm install --production       
 pm2 restart all
 exit       
EOF
